### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by luizirber** [dib-lab/scihack#1]
Let's use this issue for ideas for scihack sessions.

**Comment by luizirber** [comment]
this may be too much on the CS side, but would be interesting to try to use CQF as a backend for khmer: https://github.com/splatlab/cqf

## Comments
### daniel.standage
I think that could be good. Computationally-inclined folk could work on implementation of the core data structure, less computationally-inclined folk could work on creating & improving relevant docs / tutorials perhaps?

### luizirber 
I think it would be a good opportunity to write a few benchmarks (using `asv`?), so we can compare how backend changes affect performance/resource consumption

### camille_codon 
Testing out Cuckoo filters would also be interesting.
it's apparently "Practically Better than Bloom": https://www.cs.cmu.edu/~dga/papers/cuckoo-conext2014.pdf
(particularly, it beats it out on cache locality, and supports removals)

(moved to https://github.com/dib-lab/scihack/issues/2)

**Comment by luizirber** [comment]
@camillescott suggestion: let's write a grant/proposal for storing data on IPFS at the library.

(We can link this with the [DataRescueDavis][1] effort)

Other pointers:
 - The interplanetary wayback machine archive: https://github.com/oduwsdl/ipwb

(moved to https://github.com/dib-lab/scihack/issues/3)

[1]: http://guides.lib.ucdavis.edu/aiap_events

**Comment by ctb** [comment]
suggest paper-as-proposal rather than grant :)

**Comment by luizirber** [comment]
I created a new label (https://github.com/dib-lab/scihack/labels/ideas), let's create one issue per idea and label it with the `ideas` label instead of keeping everything here.
